# Load the configuration file
configfile: "config/config.yml"


# Get the list of samples from the data directory
(samples,) = glob_wildcards("data/files/{sample}.csv")


include: "rules/calculate_neuts.smk"


rule all:
    input:
        expand("results/fitparams/{sample}.csv", sample=samples),
        expand("results/images/{sample}.png", sample=samples),
        expand("results/images/{sample}.svg", sample=samples),
