#IC values you want saved to a file:
icvalues: [50,90,99]

# Neutralization curve plot dimensions
height: 200
width: 300

line_width: 1.5
circle_size: 25
error_bar_opacity: 0.8

# which colors to use (in order). 
colors: ["#4E79A5","#F18F3B","#E0585B","#77B7B2","#5AA155","#EDC958","#AF7AA0","#FE9EA8","#9C7561","#BAB0AC"]

# if you have an altair theme hosted on github, use this to import
github_username: 'bblarsen-sci'
github_repo: 'altair_themes'
github_branch: 'main'

# if faceted, how many columns should be used?
n_faceted_columns: 2