name: altair_neut_curves

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - altair=5.1.2
  - pandas=2.0
  - pip
  - python=3.11
  - snakefmt
  - snakemake=7.32
  - pip:
    - neutcurve==0.5.7
    - vl-convert-python

