name: altair_neut_curves

channels:
  - conda-forge
  - bioconda

dependencies:
  - altair=5.4.1
  - pandas=2.0
  - pip
  - jupyterlab
  - python=3.11
  - snakefmt
  - snakemake=7.32
  - vl-convert-python
  - pip:
    - neutcurve==0.5.7
