name: altair_neut_curves

channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - pandas=2.0
  - pip
  - jupyterlab
  - python=3.11
  - snakefmt
  - snakemake=7.32
  - pip:
    - altair
    - neutcurve==0.5.7
    - vl-convert-python

